### ISSUE TITLE
The header in the CSV file does not match the expected headers. Use the GetCSVHeader API to get the expected headers.

### ISSUE THREAD

**Issue by rocker1058** [owenr88/cognito-migrator#22]
Hello @owenr88 i hope you are doing well!!

Once again, thank you for the tool, it is very useful.

I updated the tool and I am using it with npx, at this moment I exported the users but a custom attribute was missing, I don't know the exact reason why it was missing. When importing it gives me an error indicating that this attribute is missing, cognito expects 24 and in csv it only managed to export 23.

I'll leave you some cloudwatch logs.

Miss user pool expected header - [custom:clients]

File headers total count 23, expected headers total count 24

This is how i have my custom attributes:

![imagen](https://github.com/owenr88/cognito-migrator/assets/23032907/80a8dc20-d356-47c8-acd1-debbb859e66d)

The attributes custom:databaseUserId and custom:roles are exported correctly

**Comment by owenr88** [comment]
Hey @rocker1058, thanks for raising the issue.

Can I ask a quick question - do any of your users have a value in the `custom:client` attribute?

I'm just about to deploy a new version which I'm hoping resolves this.

**Comment by owenr88** [comment]
@rocker1058 can you try the latest release please (1.2.10)? That should resolve this and hopefully the original issue too :)

**Comment by owenr88** [comment]
Actually, I don't think that will work either. Pushing a new version now!

**Comment by owenr88** [comment]
Alright, give that a go! 1.2.11 should work now

**Comment by rocker1058** [comment]
> Alright, give that a go! 1.2.11 should work now

The export works correctly with the custom attributes, but I got another error when importing.

The job says it failed because many users had an error:

[FAILED] Line Number 2 - Username should be an email ..
[FAILED] Line Number 3 - Username should be an email ..

This same thing happens for 50 users.

but it seems strange to me that you request that, I'm also going to ask aws support to get a response from them

**Comment by owenr88** [comment]
It's worth saying that the exporter is setting `"cognito:username": user.Username` when exporting. I wonder if that needs to change depending on how the user pool is configured. 

Do you have IDs in your Username field or email addresses?

In the [docs](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-using-import-tool-csv-header.html) it states:

> The cognito:username field is required and must be unique within your user pool. It can be any Unicode string. However, it cannot contain spaces or tabs.

**Comment by rocker1058** [comment]
> It's worth saying that the exporter is setting `"cognito:username": user.Username` when exporting. I wonder if that needs to change depending on how the user pool is configured.
> 
> Do you have IDs in your Username field or email addresses?
> 
> In the [docs](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-using-import-tool-csv-header.html) it states:
> 
> > The cognito:username field is required and must be unique within your user pool. It can be any Unicode string. However, it cannot contain spaces or tabs.

I have ids

cognito:username:  04789468-f071-70c1-99e0-fdc60e0c6b57,

the email is only in the field "email"

![imagen](https://github.com/owenr88/cognito-migrator/assets/23032907/97596927-0914-4539-a403-3f5e0c4e9464)
